### PR TITLE
Multi chip support

### PR DESCRIPTION
**Pull request by laborleben**
See #51.

### CODE REVIEW

**Comment by laborleben** [comment]
Hmm, github was showing the wrong commits for the merge... I fixed that by changing the base to master and set it back to development.

**Comment by DavidLP** [comment]
Black magic

**Comment by DavidLP** [comment]
Review? By the way after your colpr hack I only see data of one chip when serial scannig. Nice.

**Comment by laborleben** [comment]
Ah good to know. I will do the review in the coming days. Probably not before Monday.

**Comment by DavidLP** [comment]
To be tested before merging:

- [x] analog_scan
- [x] digital_scan
- [x] scan_ext_trigger
- [x] scan_fei4_self_trigger
- [x] scan_threshold_fast:
     - ~~Crash because on the fly scan parameter redifinition~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/commit/4d88b56c50dc2fc881039ec4907f0f63c8695a07
      - ~~Check after tuning that the scan ranges are different~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/commit/5d4ef89f64499985b579992590d55315936ae866
- [x] scan_threshold
- [x] tune_fei4
    - ~~Runs n modules times the sub scans and itself. That does not make sense.~~ wrong observation, seems fine
    - ~~tuning result (mean threshold) is far off , but otherwise everything looks fine, needs check~~ Was checked on BEAST stave and seems reasonable
- [x] tune_feedback 
     - ~~Crash in analyze since it uses not available class attributes~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/commit/5d4ef89f64499985b579992590d55315936ae866
      - ~~Crash in figure manager: AttributeError: 'FigureCanvasAgg' object has no attribute 'manager~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/commit/a423c8432d35bcf73884f7d46d095314fdee53e2
- [x] tune_gdac
- [x] tune_gdac_standard
- [x] tune_hot_pixels
- [x] tune_noise_occupancy:
    - ~~FIFO stop time out, maybe normal error and no bug~~ looks like
- [x] tune_stuck_pixel
- [x] tune_tdac
- [x] tune_fdac
- [x] tune_threshold_baseline
- [x] test_register:
   - ~~Crash of scan if one module fails test~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/pull/73/commits/95f1ae986e9c33d4e82890470a29142b9a2ff5e4
   - ~~Crash of scan if one module has corrupt data~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/pull/73/commits/a0f2c640458157a820bd02cc0ece9f8e5e0a5e25
- [x] calibrate_hit_or
   - ~~Cannot access BEAST TDC channels in parallel scan~~ fixed in commit https://github.com/SiLab-Bonn/pyBAR/pull/73/commits/4a72661906e848a25286b0bb0503047fa8772647
- [ ] prim list, meta script behavior
- [x] multi data send to different sockets

Needed features:
- [x] Proper scan parameter handling that are changed in scan loop
     - Either define scan parameter per module in serial scan mode
     - OR fix hackish programing that input run configs are not changed in the scan
      - OR reset scan parameters at the beginning of each run.
    
   --> Solution: Scan parameters, run config, and all class attributes added in the scan are now reset after the scan (commit https://github.com/SiLab-Bonn/pyBAR/commit/4d88b56c50dc2fc881039ec4907f0f63c8695a07)
- [x] Make run attributes and scan parameters that where added/changed in scan loop available for analysis
      --> Implemented in commit https://github.com/SiLab-Bonn/pyBAR/commit/5d4ef89f64499985b579992590d55315936ae866 and https://github.com/SiLab-Bonn/pyBAR/commit/a423c8432d35bcf73884f7d46d095314fdee53e2

- [x] Take last existing run cfg with warning if run cfg is given by run number and only exists for some modules_
   --> Implemented in https://github.com/SiLab-Bonn/pyBAR/pull/73/commits/7bdfafd7b59e056b1e53e0d120fdc5d36b2a2d6d with following behavior
    - if the last successfull run config does not exist for a module a warning is printed and the last existing config of a successfull run is taken for this module
    - if a run number defines the config an exception is raised if this run config does not exist (this was already the default behavior)
- [x] Fix unit tests
    --> Fixed in commit https://github.com/SiLab-Bonn/pyBAR/pull/73/commits/2aebdce55ccdf88aa25deaa1b0e2eee4b322b909
- [x] TDC handle to encapsulate single / multiple TDC channel hardware
   --> Implemented in commit https://github.com/SiLab-Bonn/pyBAR/pull/73/commits/aed036c26aed7e7a277d5997d431ff7a10e032e3

File: pybar/testing/test_interface_data/configuration.yaml [hunk 1]
```diff
@@ -1,35 +1,35 @@
-working_dir :  # Module data will be written to this path. If not given, use path of this file. Default: not given / empty
-
-dut : dut_mio_sim.yaml  # DUT hardware configuration (.yaml). Change to dut_mio_gpac.yaml for GPAC support.
-dut_configuration :  # DUT init configuration (.yaml). Change to dut_configuration_mio_gpac.yaml for GPAC support.
-
-fe_configuration :  # FE configuration file, text (.cfg) or HDF5 (.h5) file. If not given, latest valid configuration (run status FINISHED) will be taken. If a number is given, configuration from run with specified number will be taken.
```
Comment (DavidLP) [inline pybar/testing/test_interface_data/configuration.yaml]: Have to revert tomorrow

Comment (DavidLP) [reply pybar/testing/test_interface_data/configuration.yaml]: Annoying

**Comment by DavidLP** [comment]
All features are implemented and all scans are tested with 3 chips in parallel. If BEAST results make sense, (especially tuning) I will merge quickly to development to have more testers.
All possible enhancements like:
  - proper scan data handling in run base
  - proper serial/parallel scan setting
  - excluding modules in scans
  - ...

can go to a new branch then.

@laborleben If you want to comment on bugs / feature regressions do a review please.

**Comment by DavidLP** [comment]
This implementation does not work for `parallel` scans where the `configure` is based on a fe-setting. E.g. when the enable mask is ORed with an existing enable mask (e.g. see `external_trigger_scan`). A solution would be to define (like the existing `broadcast handles`) a `multi_handle` looping over all chip cfgs. This is nevertheless needed for stave support with more than one data line.

**Comment by laborleben** [comment]
@FlorianHinterkeuser : I added all promised changes. Please test.

**Comment by DavidLP** [comment]
All scans that I tested above should be retested now.

**Comment by laborleben** [comment]
This is done. I'm not aware of any issue. The branch can be merged. @DavidLP Still waiting for pyBAR_fei4_interpreter to be available on PYPI to make unit test working again.

**Comment by laborleben** [comment]
Before we merge, I want to merge development into master to have a stable release without multi chip support.
